# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal, QObject
import Settings
from Settings import Ui_Dialog
import time

class External(QObject):
    NewFingerValues = QtCore.pyqtSignal(list)

#    value=0
#    def run(self):
#        while True:
#            self.valueChanged.emit(self.value)

OPTIONS = ['None','Alt','Win',
   'Ctrl','Tab','Shift','Caps','Esc']

class Ui_AnglesValues(object):
    def setupUi(self, AnglesValues):
        AnglesValues.setObjectName("AnglesValues")
        AnglesValues.resize(675, 376)
        AnglesValues.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(AnglesValues)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ModeSelector = QtWidgets.QComboBox(self.centralwidget)
        self.ModeSelector.setObjectName("ModeSelector")
        self.ModeSelector.addItem("")
        self.ModeSelector.addItem("")
        self.gridLayout.addWidget(self.ModeSelector, 0, 0, 1, 3)
        self.ProgessLayout = QtWidgets.QVBoxLayout()
        self.ProgessLayout.setSpacing(20)
        self.ProgessLayout.setObjectName("ProgessLayout")
        self.ThumbValue = QtWidgets.QProgressBar(self.centralwidget)
        self.ThumbValue.setProperty("value", 24)
        self.ThumbValue.setObjectName("ThumbValue")
        self.ProgessLayout.addWidget(self.ThumbValue)
        self.IndexValue = QtWidgets.QProgressBar(self.centralwidget)
        self.IndexValue.setProperty("value", 24)
        self.IndexValue.setObjectName("IndexValue")
        self.ProgessLayout.addWidget(self.IndexValue)
        self.MiddleValue = QtWidgets.QProgressBar(self.centralwidget)
        self.MiddleValue.setProperty("value", 24)
        self.MiddleValue.setObjectName("MiddleValue")
        self.ProgessLayout.addWidget(self.MiddleValue)
        self.RingValue = QtWidgets.QProgressBar(self.centralwidget)
        self.RingValue.setProperty("value", 24)
        self.RingValue.setObjectName("RingValue")
        self.ProgessLayout.addWidget(self.RingValue)
        self.PinkyValue = QtWidgets.QProgressBar(self.centralwidget)
        self.PinkyValue.setProperty("value", 24)
        self.PinkyValue.setObjectName("PinkyValue")
        self.ProgessLayout.addWidget(self.PinkyValue)
        self.WristValue = QtWidgets.QProgressBar(self.centralwidget)
        self.WristValue.setProperty("value", 24)
        self.WristValue.setObjectName("WristValue")
        self.ProgessLayout.addWidget(self.WristValue)
        self.gridLayout.addLayout(self.ProgessLayout, 1, 0, 1, 1)
        self.FingersLayout = QtWidgets.QVBoxLayout()
        self.FingersLayout.setSpacing(20)
        self.FingersLayout.setObjectName("FingersLayout")
        self.ThumbLabel = QtWidgets.QLabel(self.centralwidget)
        self.ThumbLabel.setObjectName("ThumbLabel")
        self.FingersLayout.addWidget(self.ThumbLabel)
        self.IndexLabel = QtWidgets.QLabel(self.centralwidget)
        self.IndexLabel.setObjectName("IndexLabel")
        self.FingersLayout.addWidget(self.IndexLabel)
        self.MiddleLabel = QtWidgets.QLabel(self.centralwidget)
        self.MiddleLabel.setObjectName("MiddleLabel")
        self.FingersLayout.addWidget(self.MiddleLabel)
        self.RingLabel = QtWidgets.QLabel(self.centralwidget)
        self.RingLabel.setObjectName("RingLabel")
        self.FingersLayout.addWidget(self.RingLabel)
        self.PinkyLabel = QtWidgets.QLabel(self.centralwidget)
        self.PinkyLabel.setObjectName("PinkyLabel")
        self.FingersLayout.addWidget(self.PinkyLabel)
        self.WristLabel = QtWidgets.QLabel(self.centralwidget)
        self.WristLabel.setObjectName("WristLabel")
        self.FingersLayout.addWidget(self.WristLabel)
        self.gridLayout.addLayout(self.FingersLayout, 1, 1, 1, 1)
        self.KeysLayout = QtWidgets.QVBoxLayout()
        self.KeysLayout.setSpacing(20)
        self.KeysLayout.setObjectName("KeysLayout")
        self.ThumbKey = QtWidgets.QComboBox(self.centralwidget)
        self.ThumbKey.setObjectName("ThumbKey")
        self.ThumbKey.addItem("")
        self.ThumbKey.addItem("")
        self.ThumbKey.addItem("")
        self.ThumbKey.addItem("")
        self.ThumbKey.addItem("")
        self.ThumbKey.addItem("")
        self.ThumbKey.addItem("")
        self.ThumbKey.addItem("")
        self.KeysLayout.addWidget(self.ThumbKey)
        self.IndexKey = QtWidgets.QComboBox(self.centralwidget)
        self.IndexKey.setObjectName("IndexKey")
        self.IndexKey.addItem("")
        self.IndexKey.addItem("")
        self.IndexKey.addItem("")
        self.IndexKey.addItem("")
        self.IndexKey.addItem("")
        self.IndexKey.addItem("")
        self.IndexKey.addItem("")
        self.IndexKey.addItem("")
        self.KeysLayout.addWidget(self.IndexKey)
        self.MiddleKey = QtWidgets.QComboBox(self.centralwidget)
        self.MiddleKey.setObjectName("MiddleKey")
        self.MiddleKey.addItem("")
        self.MiddleKey.addItem("")
        self.MiddleKey.addItem("")
        self.MiddleKey.addItem("")
        self.MiddleKey.addItem("")
        self.MiddleKey.addItem("")
        self.MiddleKey.addItem("")
        self.KeysLayout.addWidget(self.MiddleKey)
        self.RingKey = QtWidgets.QComboBox(self.centralwidget)
        self.RingKey.setObjectName("RingKey")
        self.RingKey.addItem("")
        self.RingKey.addItem("")
        self.RingKey.addItem("")
        self.RingKey.addItem("")
        self.RingKey.addItem("")
        self.RingKey.addItem("")
        self.RingKey.addItem("")
        self.RingKey.addItem("")
        self.KeysLayout.addWidget(self.RingKey)
        self.PinkyKey = QtWidgets.QComboBox(self.centralwidget)
        self.PinkyKey.setObjectName("PinkyKey")
        self.PinkyKey.addItem("")
        self.PinkyKey.addItem("")
        self.PinkyKey.addItem("")
        self.PinkyKey.addItem("")
        self.PinkyKey.addItem("")
        self.PinkyKey.addItem("")
        self.PinkyKey.addItem("")
        self.PinkyKey.addItem("")
        self.KeysLayout.addWidget(self.PinkyKey)
        self.WristKey = QtWidgets.QComboBox(self.centralwidget)
        self.WristKey.setObjectName("WristKey")
        self.WristKey.addItem("")
        self.WristKey.addItem("")
        self.WristKey.addItem("")
        self.WristKey.addItem("")
        self.WristKey.addItem("")
        self.WristKey.addItem("")
        self.WristKey.addItem("")
        self.WristKey.addItem("")
        self.KeysLayout.addWidget(self.WristKey)
        self.gridLayout.addLayout(self.KeysLayout, 1, 2, 1, 1)
        self.CurrentKeyLayout = QtWidgets.QHBoxLayout()
        self.CurrentKeyLayout.setObjectName("CurrentKeyLayout")
        self.CurrentKey = QtWidgets.QLabel(self.centralwidget)
        self.CurrentKey.setObjectName("CurrentKey")
        self.CurrentKeyLayout.addWidget(self.CurrentKey)
        self.gridLayout.addLayout(self.CurrentKeyLayout, 2, 0, 1, 2)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 1, 3, 2, 1)
        AnglesValues.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnglesValues)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menubar.setObjectName("menubar")
        self.menuSetting_2 = QtWidgets.QMenu(self.menubar)
        self.menuSetting_2.setObjectName("menuSetting_2")
        AnglesValues.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnglesValues)
        self.statusbar.setObjectName("statusbar")
        AnglesValues.setStatusBar(self.statusbar)
        self.actionAcces_setting = QtWidgets.QAction(AnglesValues)
        self.actionAcces_setting.setObjectName("actionAcces_setting")
        self.menuSetting_2.addAction(self.actionAcces_setting)
        self.menubar.addAction(self.menuSetting_2.menuAction())

        self.retranslateUi(AnglesValues)
        QtCore.QMetaObject.connectSlotsByName(AnglesValues)


        #dialogue window
        self.Dialog = QtWidgets.QDialog()
        self.dia = Ui_Dialog()
        self.dia.setupUi(self.Dialog)
        self.Dialog.setWindowIcon(QtGui.QIcon('th.png'))
        self.actionAcces_setting.triggered.connect(self.Dialog.show)

        self.progress_bars=[self.ThumbValue,self.IndexValue,self.MiddleValue,self.RingValue,self.PinkyValue,self.WristValue]

        #threshold:
        self.thresh_thumb=self.dia.ThumbThresh.tickPosition()
        self.thresh_index = self.dia.IndexThresh.tickPosition()
        self.thresh_middle = self.dia.MiddleThresh.tickPosition()
        self.thresh_ring = self.dia.RingThresh.tickPosition()
        self.thresh_pinky = self.dia.PinkyThresh.tickPosition()
        self.thresh_wrist = self.dia.WristThresh.tickPosition()
        self.bar_origin_threshold=[self.thresh_thumb, self.thresh_index, self.thresh_middle, self.thresh_ring, self.thresh_pinky, self.thresh_wrist]


        #which key is pressed, simple mode
        self.currentKeyNumber=0

        #mode selector box
        self.update_mode()
        self.ModeSelector.currentIndexChanged.connect(self.update_mode)



        self.ext=External()
        self.ext.NewFingerValues.connect(self.ChangingValue)



    def init_threshold_sliders(self,values):
        self.dia.ThumbThresh.setValue(values[0])
        self.dia.IndexThresh.setValue(values[1])
        self.dia.MiddleThresh.setValue(values[2])
        self.dia.RingThresh.setValue(values[3])
        self.dia.PinkyThresh.setValue(values[4])
        self.dia.WristThresh.setValue(values[5])

    def update_threshold(self):
        self.thresh_thumb = self.dia.ThumbThresh.value()
        self.thresh_index = self.dia.IndexThresh.value()
        self.thresh_middle = self.dia.MiddleThresh.value()
        self.thresh_ring = self.dia.RingThresh.value()
        self.thresh_pinky = self.dia.PinkyThresh.value()
        self.thresh_wrist = self.dia.PinkyThresh.value()
        self.bar_origin_threshold = [self.thresh_thumb, self.thresh_index, self.thresh_middle, self.thresh_ring,
                                     self.thresh_pinky,self.thresh_wrist]

    #def update_progress(self):
    #    self.calc= External()
    #    self.calc.valueChanged.connect(self.onValueChanged)
    #    self.calc.start()

    def ChangingValue(self,value):
        self.ThumbValue.setValue(value[5])
        self.IndexValue.setValue(value[4])
        self.MiddleValue.setValue(value[3])
        self.RingValue.setValue(value[2])
        self.PinkyValue.setValue(value[1])
        self.WristValue.setValue(value[0])

        if self.ModeSelector.currentText() == 'Simple Mode':
            if self.ThumbValue.value()>= self.thresh_thumb:
                self.currentKeyNumber+=1

                if self.currentKeyNumber>=len(OPTIONS):
                    self.currentKeyNumber=0
                self.CurrentKey.setText(OPTIONS[self.currentKeyNumber])


    def update_mode(self):
        if self.ModeSelector.currentText()=='Simple Mode':
            self.CurrentKey.setHidden(False)
            self.ThumbKey.hide()
            self.IndexKey.hide()
            self.MiddleKey.hide()
            self.RingKey.hide()
            self.PinkyKey.hide()
            self.WristKey.hide()
        else:
            self.CurrentKey.setHidden(True)
            self.ThumbKey.show()
            self.IndexKey.show()
            self.MiddleKey.show()
            self.RingKey.show()
            self.PinkyKey.show()
            self.WristKey.show()




    def retranslateUi(self, AnglesValues):
        _translate = QtCore.QCoreApplication.translate
        AnglesValues.setWindowTitle(_translate("AnglesValues", "Angle Value"))
        self.ModeSelector.setItemText(0, _translate("AnglesValues", "Simple Mode"))
        self.ModeSelector.setItemText(1, _translate("AnglesValues", "Advanced Mode"))
        self.ThumbLabel.setText(_translate("AnglesValues", "Thumb"))
        self.IndexLabel.setText(_translate("AnglesValues", "Index"))
        self.MiddleLabel.setText(_translate("AnglesValues", "Middle"))
        self.RingLabel.setText(_translate("AnglesValues", "Ring"))
        self.PinkyLabel.setText(_translate("AnglesValues", "Pinky"))
        self.WristLabel.setText(_translate("AnglesValues", "Wrist"))
        self.ThumbKey.setItemText(0, _translate("AnglesValues", "None"))
        self.ThumbKey.setItemText(1, _translate("AnglesValues", "Alt"))
        self.ThumbKey.setItemText(2, _translate("AnglesValues", "Win"))
        self.ThumbKey.setItemText(3, _translate("AnglesValues", "Ctrl"))
        self.ThumbKey.setItemText(4, _translate("AnglesValues", "Tab"))
        self.ThumbKey.setItemText(5, _translate("AnglesValues", "Shift"))
        self.ThumbKey.setItemText(6, _translate("AnglesValues", "Caps"))
        self.ThumbKey.setItemText(7, _translate("AnglesValues", "Esc"))
        self.IndexKey.setItemText(0, _translate("AnglesValues", "None"))
        self.IndexKey.setItemText(1, _translate("AnglesValues", "Alt"))
        self.IndexKey.setItemText(2, _translate("AnglesValues", "Win"))
        self.IndexKey.setItemText(3, _translate("AnglesValues", "Ctrl"))
        self.IndexKey.setItemText(4, _translate("AnglesValues", "Tab"))
        self.IndexKey.setItemText(5, _translate("AnglesValues", "Shift"))
        self.IndexKey.setItemText(6, _translate("AnglesValues", "Caps"))
        self.IndexKey.setItemText(7, _translate("AnglesValues", "Esc"))
        self.MiddleKey.setItemText(0, _translate("AnglesValues", "None"))
        self.MiddleKey.setItemText(1, _translate("AnglesValues", "Alt"))
        self.MiddleKey.setItemText(2, _translate("AnglesValues", "Win"))
        self.MiddleKey.setItemText(3, _translate("AnglesValues", "Tab"))
        self.MiddleKey.setItemText(4, _translate("AnglesValues", "Shift"))
        self.MiddleKey.setItemText(5, _translate("AnglesValues", "Caps"))
        self.MiddleKey.setItemText(6, _translate("AnglesValues", "Esc"))
        self.RingKey.setItemText(0, _translate("AnglesValues", "None"))
        self.RingKey.setItemText(1, _translate("AnglesValues", "Alt"))
        self.RingKey.setItemText(2, _translate("AnglesValues", "Win"))
        self.RingKey.setItemText(3, _translate("AnglesValues", "Ctrl"))
        self.RingKey.setItemText(4, _translate("AnglesValues", "Tab"))
        self.RingKey.setItemText(5, _translate("AnglesValues", "Shift"))
        self.RingKey.setItemText(6, _translate("AnglesValues", "Caps"))
        self.RingKey.setItemText(7, _translate("AnglesValues", "Esc"))
        self.PinkyKey.setItemText(0, _translate("AnglesValues", "None"))
        self.PinkyKey.setItemText(1, _translate("AnglesValues", "Alt"))
        self.PinkyKey.setItemText(2, _translate("AnglesValues", "Win"))
        self.PinkyKey.setItemText(3, _translate("AnglesValues", "Ctrl"))
        self.PinkyKey.setItemText(4, _translate("AnglesValues", "Tab"))
        self.PinkyKey.setItemText(5, _translate("AnglesValues", "Shift"))
        self.PinkyKey.setItemText(6, _translate("AnglesValues", "Caps"))
        self.PinkyKey.setItemText(7, _translate("AnglesValues", "Esc"))
        self.WristKey.setItemText(0, _translate("AnglesValues", "None"))
        self.WristKey.setItemText(1, _translate("AnglesValues", "Alt"))
        self.WristKey.setItemText(2, _translate("AnglesValues", "Win"))
        self.WristKey.setItemText(3, _translate("AnglesValues", "Ctrl"))
        self.WristKey.setItemText(4, _translate("AnglesValues", "Tab"))
        self.WristKey.setItemText(5, _translate("AnglesValues", "Shift"))
        self.WristKey.setItemText(6, _translate("AnglesValues", "Caps"))
        self.WristKey.setItemText(7, _translate("AnglesValues", "Esc"))
        self.CurrentKey.setText(_translate("AnglesValues", "None"))
        self.menuSetting_2.setTitle(_translate("AnglesValues", "Setting"))
        self.actionAcces_setting.setText(_translate("AnglesValues", "Acces setting"))
