# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Settings
from Settings import Ui_Dialog


class Ui_AnglesValues(object):
    def setupUi(self, AnglesValues):
        AnglesValues.setObjectName("AnglesValues")
        AnglesValues.resize(675, 376)
        AnglesValues.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(AnglesValues)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 3)
        self.ProgessLayout = QtWidgets.QVBoxLayout()
        self.ProgessLayout.setSpacing(20)
        self.ProgessLayout.setObjectName("ProgessLayout")
        self.ThumbValue = QtWidgets.QProgressBar(self.centralwidget)
        self.ThumbValue.setProperty("value", 24)
        self.ThumbValue.setObjectName("ThumbValue")
        self.ProgessLayout.addWidget(self.ThumbValue)
        self.IndexValue = QtWidgets.QProgressBar(self.centralwidget)
        self.IndexValue.setProperty("value", 24)
        self.IndexValue.setObjectName("IndexValue")
        self.ProgessLayout.addWidget(self.IndexValue)
        self.MiddleValue = QtWidgets.QProgressBar(self.centralwidget)
        self.MiddleValue.setProperty("value", 24)
        self.MiddleValue.setObjectName("MiddleValue")
        self.ProgessLayout.addWidget(self.MiddleValue)
        self.RingValue = QtWidgets.QProgressBar(self.centralwidget)
        self.RingValue.setProperty("value", 24)
        self.RingValue.setObjectName("RingValue")
        self.ProgessLayout.addWidget(self.RingValue)
        self.PinkyValue = QtWidgets.QProgressBar(self.centralwidget)
        self.PinkyValue.setProperty("value", 24)
        self.PinkyValue.setObjectName("PinkyValue")
        self.ProgessLayout.addWidget(self.PinkyValue)
        self.gridLayout.addLayout(self.ProgessLayout, 1, 0, 1, 1)
        self.FingersLayout = QtWidgets.QVBoxLayout()
        self.FingersLayout.setSpacing(20)
        self.FingersLayout.setObjectName("FingersLayout")
        self.ThumbLabel = QtWidgets.QLabel(self.centralwidget)
        self.ThumbLabel.setObjectName("ThumbLabel")
        self.FingersLayout.addWidget(self.ThumbLabel)
        self.IndexLabel = QtWidgets.QLabel(self.centralwidget)
        self.IndexLabel.setObjectName("IndexLabel")
        self.FingersLayout.addWidget(self.IndexLabel)
        self.MiddleLabel = QtWidgets.QLabel(self.centralwidget)
        self.MiddleLabel.setObjectName("MiddleLabel")
        self.FingersLayout.addWidget(self.MiddleLabel)
        self.RingLabel = QtWidgets.QLabel(self.centralwidget)
        self.RingLabel.setObjectName("RingLabel")
        self.FingersLayout.addWidget(self.RingLabel)
        self.PinkyLabel = QtWidgets.QLabel(self.centralwidget)
        self.PinkyLabel.setObjectName("PinkyLabel")
        self.FingersLayout.addWidget(self.PinkyLabel)
        self.gridLayout.addLayout(self.FingersLayout, 1, 1, 1, 1)
        self.KeysLayout = QtWidgets.QVBoxLayout()
        self.KeysLayout.setObjectName("KeysLayout")
        self.ThumbKey = QtWidgets.QLabel(self.centralwidget)
        self.ThumbKey.setObjectName("ThumbKey")
        self.KeysLayout.addWidget(self.ThumbKey)
        self.IndexKey = QtWidgets.QLabel(self.centralwidget)
        self.IndexKey.setObjectName("IndexKey")
        self.KeysLayout.addWidget(self.IndexKey)
        self.MiddleKey = QtWidgets.QLabel(self.centralwidget)
        self.MiddleKey.setObjectName("MiddleKey")
        self.KeysLayout.addWidget(self.MiddleKey)
        self.RingKey = QtWidgets.QLabel(self.centralwidget)
        self.RingKey.setObjectName("RingKey")
        self.KeysLayout.addWidget(self.RingKey)
        self.PinkyKey = QtWidgets.QLabel(self.centralwidget)
        self.PinkyKey.setObjectName("PinkyKey")
        self.KeysLayout.addWidget(self.PinkyKey)
        self.gridLayout.addLayout(self.KeysLayout, 1, 2, 1, 1)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 1, 3, 2, 1)
        self.CurrentKeyLayout = QtWidgets.QHBoxLayout()
        self.CurrentKeyLayout.setObjectName("CurrentKeyLayout")
        self.CurrentKey = QtWidgets.QLabel(self.centralwidget)
        self.CurrentKey.setObjectName("CurrentKey")
        self.CurrentKeyLayout.addWidget(self.CurrentKey)
        self.gridLayout.addLayout(self.CurrentKeyLayout, 2, 0, 1, 2)
        AnglesValues.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnglesValues)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 22))
        self.menubar.setObjectName("menubar")
        self.menuSetting_2 = QtWidgets.QMenu(self.menubar)
        self.menuSetting_2.setObjectName("menuSetting_2")
        AnglesValues.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnglesValues)
        self.statusbar.setObjectName("statusbar")
        AnglesValues.setStatusBar(self.statusbar)
        self.actionAcces_setting = QtWidgets.QAction(AnglesValues)
        self.actionAcces_setting.setObjectName("actionAcces_setting")
        self.menuSetting_2.addAction(self.actionAcces_setting)
        self.menubar.addAction(self.menuSetting_2.menuAction())

        self.retranslateUi(AnglesValues)
        QtCore.QMetaObject.connectSlotsByName(AnglesValues)

        self.retranslateUi(AnglesValues)
        QtCore.QMetaObject.connectSlotsByName(AnglesValues)



        self.Dialog = QtWidgets.QDialog()
        self.dia = Ui_Dialog()
        self.dia.setupUi(self.Dialog)
        self.Dialog.setWindowIcon(QtGui.QIcon('th.png'))
        self.actionAcces_setting.triggered.connect(self.Dialog.show)



        #threshold:
        self.thresh_thumb=self.dia.ThumbThresh.tickPosition()
        self.thresh_index = self.dia.IndexThresh.tickPosition()
        self.thresh_middle = self.dia.MiddleThresh.tickPosition()
        self.thresh_ring = self.dia.RingThresh.tickPosition()
        self.thresh_pinky = self.dia.PinkyThresh.tickPosition()
        self.bar_origin_threshold=[self.thresh_thumb, self.thresh_index, self.thresh_middle, self.thresh_ring, self.thresh_pinky]


    def retranslateUi(self, AnglesValues):
        _translate = QtCore.QCoreApplication.translate
        AnglesValues.setWindowTitle(_translate("AnglesValues", "Angle Value"))
        self.comboBox.setItemText(0, _translate("AnglesValues", "Simple Mode"))
        self.comboBox.setItemText(1, _translate("AnglesValues", "Advanced Mode"))
        self.ThumbLabel.setText(_translate("AnglesValues", "Thumb"))
        self.IndexLabel.setText(_translate("AnglesValues", "Index"))
        self.MiddleLabel.setText(_translate("AnglesValues", "Middle"))
        self.RingLabel.setText(_translate("AnglesValues", "Ring"))
        self.PinkyLabel.setText(_translate("AnglesValues", "Pinky"))
        self.ThumbKey.setText(_translate("AnglesValues", "None"))
        self.IndexKey.setText(_translate("AnglesValues", "None"))
        self.MiddleKey.setText(_translate("AnglesValues", "None"))
        self.RingKey.setText(_translate("AnglesValues", "None"))
        self.PinkyKey.setText(_translate("AnglesValues", "None"))
        self.CurrentKey.setText(_translate("AnglesValues", "None"))
        self.menuSetting_2.setTitle(_translate("AnglesValues", "Setting"))
        self.actionAcces_setting.setText(_translate("AnglesValues", "Acces setting"))


