# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hand2key.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 529)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ThumbBar = QtWidgets.QProgressBar(Dialog)
        self.ThumbBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThumbBar.setProperty("value", 24)
        self.ThumbBar.setObjectName("ThumbBar")
        self.verticalLayout.addWidget(self.ThumbBar)
        self.IndexBar = QtWidgets.QProgressBar(Dialog)
        self.IndexBar.setProperty("value", 24)
        self.IndexBar.setObjectName("IndexBar")
        self.verticalLayout.addWidget(self.IndexBar)
        self.MiddleBar = QtWidgets.QProgressBar(Dialog)
        self.MiddleBar.setProperty("value", 24)
        self.MiddleBar.setObjectName("MiddleBar")
        self.verticalLayout.addWidget(self.MiddleBar)
        self.RingBar = QtWidgets.QProgressBar(Dialog)
        self.RingBar.setProperty("value", 24)
        self.RingBar.setObjectName("RingBar")
        self.verticalLayout.addWidget(self.RingBar)
        self.PinkyBar = QtWidgets.QProgressBar(Dialog)
        self.PinkyBar.setProperty("value", 24)
        self.PinkyBar.setObjectName("PinkyBar")
        self.verticalLayout.addWidget(self.PinkyBar)
        self.ThumbThresh = QtWidgets.QSlider(Dialog)
        self.ThumbThresh.setOrientation(QtCore.Qt.Horizontal)
        self.ThumbThresh.setObjectName("ThumbThresh")
        self.verticalLayout.addWidget(self.ThumbThresh)
        self.IndexThresh = QtWidgets.QSlider(Dialog)
        self.IndexThresh.setOrientation(QtCore.Qt.Horizontal)
        self.IndexThresh.setObjectName("IndexThresh")
        self.verticalLayout.addWidget(self.IndexThresh)
        self.MiddleThresh = QtWidgets.QSlider(Dialog)
        self.MiddleThresh.setOrientation(QtCore.Qt.Horizontal)
        self.MiddleThresh.setObjectName("MiddleThresh")
        self.verticalLayout.addWidget(self.MiddleThresh)
        self.RingThresh = QtWidgets.QSlider(Dialog)
        self.RingThresh.setOrientation(QtCore.Qt.Horizontal)
        self.RingThresh.setObjectName("RingThresh")
        self.verticalLayout.addWidget(self.RingThresh)
        self.PinkyThresh = QtWidgets.QSlider(Dialog)
        self.PinkyThresh.setOrientation(QtCore.Qt.Horizontal)
        self.PinkyThresh.setObjectName("PinkyThresh")
        self.verticalLayout.addWidget(self.PinkyThresh)
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_4.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_2.setText(_translate("Dialog", "Use shifter"))
        self.checkBox.setText(_translate("Dialog", "Sound"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
